config/routes.rb
Rails.application.routes.draw do

  post "paired", to: "partnerships#paired"
  post "unpaired", to: "partnerships#unpaired"

  get "partnership/:id", to: "partnerships#show", as: "partner"

  get '/auth/:provider/callback', to: "sessions#create"
  root 'static_pages#home'
  get "static_pages/dashboard", to: "static_pages#dashboard", as: "dashboard"

  delete 'logout', to: 'sessions#destroy'
  resources :users
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :user_languages
  has_many :users, through: :user_languages
  validates :name, presence: true
end

app/models/partnership.rb
class Partnership < ActiveRecord::Base
  belongs_to :user
  belongs_to :paired, class_name: "User"
  
  enum condition: %w(potential reject pending matched)

  scope :reject, -> { where(condition: 1) }
  scope :pending, -> { where(condition: 2) }
  scope :matched, -> { where(condition: 3) }

  def self.new_matches(current_user)
    potential_matches = []
    pending_matches = []
    Partnership.all.each do |partner|
      if partner.condition == "pending" && partner.user_id != current_user.id
        pending_matches << partner
      end
    end
    Partnership.all.each do |partner|
      if partner.condition == "potential" && partner.user_id != current_user.id
        pending_matches << partner
      end
    end
    potential_matches.flatten + pending_matches.flatten
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_languages
  has_many :languages, through: :user_languages

  has_many :partnerships
  has_many :paireds, through: :partnerships

  has_many :inverse_partners, :class_name => "Partnership", :foreign_key => "partner_id"
  has_many :inverse_partners, :through => :inverse_partners, :source => :user

  validates :nickname, presence: true
  validates :details, length: { maximum: 500 }

  def self.find_or_create_from_auth(data)
    user = User.find_or_create_by(provider: data.provider, uid: data.uid)
    user.nickname = data.info.nickname
    user.image_url = data.info.image_url

    user.save
    user
  end


end

app/models/user_language.rb
class UserLanguage < ActiveRecord::Base
  belongs_to :user
  belongs_to :language
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  # before_action :authorize!

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize!
    if current_user.nil?
      redirect_to root_path
    end
  end
end

app/controllers/partnerships_controller.rb
class PartnershipsController < ApplicationController

  def paired
    @match = current_user.partnerships.find_by(partner_id: params[:partner_id])
    if @match.save
      if @match.condition == "pending"
        @match.condition = "matched"
        @match.save
        flash[:success] = "Pair added!"
        redirect_to dashboard_path(current_user)

      elsif @match.condition == "potential"
        @match.condition = "pending"
        @match.save
        flash[:notice] = "soon to be paired"
        redirect_to partner_path(current_user)
      else
        flash[:error] = "Can't pair up with this person"
        redirect_to partner_path(current_user)
      end
    else
      flash[:notice] = "Unable to add Pair."
      redirect_to partner_path(current_user)
    end
  end

  def unpaired
    @match = current_user.partnerships.find_by(partner_id: params[:partner_id])
    if @match.save
      @match.condition = "reject"
      @match.save
      flash[:alert] = "They won't try to pair with you!."
      redirect_to partner_path(current_user)
    else
      flash[:notice] = "Unable to add Pair."
      redirect_to partner_path(current_user)
    end
  end

  def show
    partner_id = Partnership.new_matches(current_user).sample.partner_id
    @partner = User.find_by(id: partner_id)
  end

  def new
    @partnership = Partnership.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth(auth_hash)

    if user
      session[:user_id] = user.id
      generate_partners
      if user.languages.empty?
        redirect_to edit_user_path(user)
      else
        redirect_to dashboard_path
      end
      user.save
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def auth_hash
    request.env["omniauth.auth"]
  end

  def generate_partners
    User.all.each do |user1|
      User.all.each do |user2|
        Partnership.create(user_id: user1.id, partner_id: user2.id, condition: 0) unless user1.id == user2.id
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authorize!

  def home
  end

  def dashboard
    @partnerships = Partnership.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def edit
    @user = current_user
    @languages = Language.all
  end

  def update
    @user = current_user
    if @user.update(user_params)
      language_add
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def language_add
    if params["language"].present?
     params["language"].each do |lang|
       @user.languages << Language.find_by(name: lang)
     end
   end
  end

  def additional_info_added?
    current_user.details
  end

  def user_params
    params.require(:user).permit(:details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/partnerships_helper.rb
module PartnershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="messages">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "flash-#{name}" %>
      <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/partnerships/edit.html.erb
<h1>Editing Partnership</h1>

<%= render 'form' %>

<%= link_to 'Show', @partnership %> |
<%= link_to 'Back', partnerships_path %>

app/views/partnerships/new.html.erb
<h1>New Partnership</h1>

<%= render 'form' %>

<%= link_to 'Back', partnerships_path %>

app/views/partnerships/show.html.erb
Your new match below:

<h3><%= @partner.nickname %> </h3><br>
<%= image_tag @partner.image_url %> <br>

<%= button_to "Pair", paired_path(partner_id: @partner.id)  %>

<%= button_to "Unpair", unpaired_path(partner_id: @partner.id) %>

<%= link_to "Back to Your Dashboard", dashboard_path %>

app/views/static_pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <h1>Welcome to your Pair Dashboard <%= current_user.nickname %> </h1>

  </div>
    <%= image_tag current_user.image_url %>

<div class="fave_langs">
  <h3>Your favorite languages</h3>
  <ul>
    <% current_user.languages.map do |l| %>
      <li><%= l.name %></li>
    <% end %>
  </ul>
</div>

  <div class="pair-index">
    <h2>People You want to Pair With</h2>
  </div>

  <div class="row">
    <div class="partner_path">
      <%= link_to "Find Pair", partner_path(current_user.id) %>
  </div>
  </div>

  <div class="row">
    <div class="logout">
      <%= link_to "Log Out", logout_path, method: :delete %>
  </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid container-home">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1 class="home">Welcome to Pairr</h1>
    <h2 class="home">Looking for Love in all the wrong places?</h2>
    <%= link_to "Login with Github", "/auth/github", class: "btn btn-lg btn-default btn-home" %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/edit.html.erb
<h1>User Information</h1>
<h2>Add details to appear more enticing to other Programmers</h2>

<h3>Some more details:</h3>
<%= form_for @user do |f| %>
  <%= f.label :details %> <br>
  <%= f.text_area :details, rows: 10, cols: 40 %> <br>


  <h5>Your Preferred Languages</h5>
  <% @languages.map do |l| %>
    <input type="checkbox" name="language[<%= l.name %>]">
    <label for="<%= l.name %>"><%= l.name %></label>
  <% end %>

  <%= f.submit "That's what I'm about!" %>
<% end %>

app/views/users/show.html.erb
<h1>Pick a Pair</h1>

<div class="row">
  <div class="selection">
    <div class="identifier">
      <%# @user.image_url %>
      <%# @user.nickname %>
    </div>

    <div class="content">
      <p>
        <%= @user.details %>
      </p>

      <h5>Skills:</h5>

      <%= @user.languages.pluck(:name) %>
    </div>

    <div class="user-actions">
      <div class="row">
        <%= button_to("Yes", partnerships_path(pair_id: @user.id, condition: "Pending"))  %>

        <%= button_to("No", partnerships_path(pair_id: @user.id, condition: "Reject"))  %>
      </div>
    </div>

  </div>

</div>